#Destination: B = bidir_ip(src_ip and dst_ip), D = dst_ip, S = src_ip
#timeout: minimal capture time in seconds, use -1 for unlimited
#packet limit : minimal number of packets to capture, use -1 for nlimited (default)

- Default:
    Score: 10
    Destination: S
    Packets: 100
    Timeout: 20
- Abusive:
    Spam:
      Score: 10
    Harassment:
      Score: 10
    Child:
      Score: 10
    Sexual:
      Score: 10
    Violence:
      Score: 10
- Malware:
    Virus:
      Score: 10
    Worm:
      Score: 10
    Trojan:
      Score: 10
    Spyware:
      Score: 10
    Dialer:
      Score: 10
    Rootkit:
      Score: 10
- Recon:
    Scanning:
      Score: 1
    Sniffing:
      Score: 10
    SocialEngineering:
      Score: 10
    Searching:
      Score: 10
- Attempt:
    Exploit:
      Score: 10
    Login:
      Score: 10
    NewSignature:
      Score: 10
- Intrusion:
    AdminCompromise:
      Score: 10
    UserCompromise:
      Score: 10
    AppCompromise:
      Score: 10
    Botnet:
      Score: 10
- Availability:
    DoS:
      Score: 10
    DDoS:
      Score: 10
    Sabotage:
      Score: 10
    Outage:
      Score: 10
- Information:
    UnauthorizedAccess:
      Score: 10
    UnauthorizedModification:
      Score: 10
- Fraud:
    UnauthorizedUsage:
      Score: 10
    Copyright:
      Score: 10
    Masquerade:
      Score: 10
    Phishing:
      Score: 10
    Scam:
      Score: 10
- Vulnerable:
    Open:
      Score: 10
    Config:
      Score: 10
- Anomaly:
    Traffic:
      Score: 10
    Connection:
      Score: 10
    Protocol:
      Score: 10
    System:
      Score: 10
    Application:
      Score: 10
    Behaviour:
      Score: 10
- NotInConfig:
      Score: 10
